# This file generates the GitHub Actions matrix
# For simple board + shield combinations, add them
# to the top level board and shield arrays, for more
# control, add individual board + shield combinations to
# the `include` property, e.g:
#
include:
   - board: seeeduino_xiao_ble
     shield: clog_v2_left
   - board: seeeduino_xiao_ble
     shield: clog_v2_right
   - board: seeeduino_xiao_ble
     shield: xiao_settings_reset
