manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: sporkus
      url-base: https://github.com/sporkus
  projects:
    - name: zmk
      remote: sporkus
      revision: create-board-test
      import: app/west.yml
  self:
    path: config

