file_format: "1"
id: le_chiffre_stm32
name: Le Chiffre (stm32)
type: board
arch: arm
features:
  - keys
  - display
  - encoders
outputs:
  - usb
url: https://github.com/sporkus/le_chiffre_keyboard_stm32
